/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bolsav;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author geova
 */
public class Client_BolsaV extends javax.swing.JFrame {

    public CliImpl client;

    /**
     * Creates new form Client_BolsaV
     */
    public Client_BolsaV(CliImpl client) {
        initComponents();
        jPMonitor.setVisible(true);
        this.client = client;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPMonitor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBRefresh = new javax.swing.JButton();
        jBBuy = new javax.swing.JButton();
        jBMonitor = new javax.swing.JButton();
        jPWallet = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBRegister = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jBSell = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Empresa", "Valor", "Quantidade Disponível"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        jBRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRefreshActionPerformed(evt);
            }
        });

        jBBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buy.png"))); // NOI18N
        jBBuy.setText("Comprar");
        jBBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuyActionPerformed(evt);
            }
        });

        jBMonitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/progress-report.png"))); // NOI18N
        jBMonitor.setText("Monitorar");
        jBMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMonitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPMonitorLayout = new javax.swing.GroupLayout(jPMonitor);
        jPMonitor.setLayout(jPMonitorLayout);
        jPMonitorLayout.setHorizontalGroup(
            jPMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMonitorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMonitorLayout.createSequentialGroup()
                        .addGap(0, 417, Short.MAX_VALUE)
                        .addComponent(jBRefresh))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPMonitorLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jBBuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBMonitor)
                .addGap(43, 43, 43))
        );
        jPMonitorLayout.setVerticalGroup(
            jPMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMonitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBuy)
                    .addComponent(jBMonitor))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Monitor", jPMonitor);

        jLabel7.setText("Empresa:");

        jLabel8.setText("Quantidade:");

        jLabel9.setText("Preço Máximo:");

        jBRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buy.png"))); // NOI18N
        jBRegister.setText("Cadastrar");
        jBRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegisterActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Disponível para Venda");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Empresa", "Quantidade", "Preço", "Disponível"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        jBSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping.png"))); // NOI18N
        jBSell.setText("Vender");
        jBSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPWalletLayout = new javax.swing.GroupLayout(jPWallet);
        jPWallet.setLayout(jPWalletLayout);
        jPWalletLayout.setHorizontalGroup(
            jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPWalletLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPWalletLayout.createSequentialGroup()
                        .addGroup(jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPWalletLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(22, 22, 22))
                                .addGroup(jPWalletLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel8)
                                    .addGap(24, 24, 24)))
                            .addGroup(jPWalletLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)))
                        .addGroup(jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField8)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jBRegister))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPWalletLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jBSell)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPWalletLayout.setVerticalGroup(
            jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPWalletLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPWalletLayout.createSequentialGroup()
                        .addGroup(jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBRegister))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSell)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Minha Carteira", jPWallet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRefreshActionPerformed
        //atualizar dados da tabela
        setUpTableMonitor();
    }//GEN-LAST:event_jBRefreshActionPerformed

    private void jBBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuyActionPerformed
        int linha = jTable1.getSelectedRow();
        if (linha != -1) {
            if(jTable1.getValueAt(linha, 2).toString().compareTo("0")!=0){
            //código para mostrar um panel na caixa de diálogo
            JTextField priceField = new JTextField(5);
            JTextField qntdField = new JTextField(5);
            Object[] message = {"Informe preço máximo e quantidade desejada\n\nPreço:", priceField,"Quantidade:", qntdField};
            
            int result = JOptionPane.showConfirmDialog(null, message, "Compra", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                double price = Double.parseDouble(priceField.getText().replace(".", ","));
                int qntd = Integer.parseInt(qntdField.getText());
            }
            String company = jTable1.getValueAt(linha, 0).toString();
            //registrar compra
            }else{
                int op = JOptionPane.showConfirmDialog(null, "", "Login", JOptionPane.OK_CANCEL_OPTION);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma ação selecionada");
        }

    }//GEN-LAST:event_jBBuyActionPerformed

    private void jBSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSellActionPerformed
        int linha = jTable2.getSelectedRow();
        if (linha != -1) {
            String company = jTable2.getValueAt(linha, 0).toString();
            int qntd = Integer.parseInt(jTable2.getValueAt(linha, 1).toString());
            Double price = Double.parseDouble(jTable2.getValueAt(linha, 2).toString().replace(".", ","));
            //buscar a stock ja criada para atualizar a disponibilidade
            Stock stock = new Stock(company, qntd, price);
            stock.setAvailable(true);
            client.insertStock(stock);
            setUpTableWallet();
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma ação selecionada");
        }
    }//GEN-LAST:event_jBSellActionPerformed

    private void jBRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegisterActionPerformed
        if (!(jTextField7.getText().isEmpty() || jTextField8.getText().isEmpty() || jTextField9.getText().isEmpty())) {
            String company = jTextField7.getText();
            int qntd = Integer.parseInt(jTextField8.getText());
            Double price = Double.parseDouble(jTextField9.getText());
            Stock stock = new Stock(company, qntd, price);
            stock.setAvailable(jCheckBox1.isSelected());
            client.insertStock(stock);
            setUpTableWallet();
        }
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
    }//GEN-LAST:event_jBRegisterActionPerformed

    private void jBMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMonitorActionPerformed
        int linha = jTable1.getSelectedRow();
        if (linha != -1) {
            try {
                //implementar monitoramento
                client.server.subscribe(client, jTable1.getValueAt(linha, 0).toString());
            } catch (RemoteException ex) {
                Logger.getLogger(Client_BolsaV.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma ação selecionada");
        }
    }//GEN-LAST:event_jBMonitorActionPerformed

    void setUpTableMonitor() {
        try {
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            //atualizar a tabela a partir dos dados em produtos
            tableModel.setRowCount(0);
            int qntd;
            for (StockCli s : client.server.getStocks()) {
                if(s.id != client.id){
                if (!s.getStock().isAvailable()) {
                    qntd = 0;
                } else {
                    qntd = s.getStock().getQt();
                }
                tableModel.addRow(new Object[]{s.getStock().getCompany(), s.getStock().getPrice(), qntd});
            }
            }
            
            jTable1.setModel(tableModel);
            tableModel.fireTableDataChanged();
        } catch (RemoteException ex) {
            Logger.getLogger(Client_BolsaV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void setUpTableWallet() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        //atualizar a tabela a partir dos dados em produtos
        tableModel.setRowCount(0);
        for (Stock s : client.getStocks()) {
            tableModel.addRow(new Object[]{s.getCompany(), s.getQt(), s.getPrice(), s.isAvailable()});
        }
        jTable2.setModel(tableModel);
        tableModel.fireTableDataChanged();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_BolsaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_BolsaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_BolsaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_BolsaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_BolsaV().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuy;
    private javax.swing.JButton jBMonitor;
    private javax.swing.JButton jBRefresh;
    private javax.swing.JButton jBRegister;
    private javax.swing.JButton jBSell;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPMonitor;
    private javax.swing.JPanel jPWallet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
